version: "3.0"

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment: 
      - FLASK_APP=pybo
      - FLASK_ENV=development
    command:
      flask run --host=0.0.0.0
      # - flask db init